# RocketMQ Broker 配置
brokerIP1=127.0.0.1
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
namesrvAddr=rmq-namesrv:9876
storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
autoCreateTopicEnable=true
