# ==================== Worker 配置 ====================
workerId=DockerWorker01
storePathRootDir=/tmp/connect-store

# ==================== REST API ====================
httpPort=8082

# ==================== RocketMQ 连接 ====================
namesrvAddr=rmq-namesrv:9876
clusterName=DefaultCluster

# ==================== ACL（关闭） ====================
aclEnable=false

# ==================== 插件目录（核心配置） ====================
pluginPaths=/usr/local/connector-plugins
